### ISSUE TITLE
Leak detection - Leak Details - Typo

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#1]
Leak status is misspelled as "Leak tatus" -- please correct to "Leak Status"
Please change "Repair_required" to "Repair Required"

![image](https://cloud.githubusercontent.com/assets/7118831/2615551/7030cb60-bbfb-11e3-94c9-c0fa27892cc3.png)

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed complete.  Will close.
