### ISSUE TITLE
Leak Detection - Leak Details - Layout

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#10]
The SR Number will need to be edited by field personnel and populated in the field.  Please make the field editable.

![image](https://cloud.githubusercontent.com/assets/7118831/2646156/706b5220-bf3a-11e3-9e21-1bbd0efda32b.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
