### ISSUE TITLE
Leak Detection - Leak - Data structure

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#100]
Please remove the following from the app (edit leak):

Depth
Confirmed
Repair Required

**Comment by kanglu666** [comment]
do you want to remove these three fields from the database? or just remove them from the app, leave them in the db schema

**Comment by alanfoster99** [comment]
Just remove from app for now

Alan E. Foster

Senior Geospatial Analyst, KCI Technologies, Inc.
1.410.316.0812tel:1.410.316.0812
alan.foster@kci.commailto:alan.foster@kci.com

Lead, UAMD Data Management Section
1.410.396.0022tel:1.410.396.0022

On Jun 18, 2014, at 12:05, "lu" <notifications@github.com<mailto:notifications@github.com>> wrote:

do you want to remove these three fields from the database? or just remove them from the app, leave them in the db schema

**Comment by kanglu666** [comment]
updated, please clear browser cache and test

**Comment by alanfoster99** [comment]
Confirmed and closed
