### ISSUE TITLE
Leak Detection - Email Report - Subject

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#104]
Please add the asset type and asset ID to the subject line of the emails being sent.

For example:
"Leak reported on hydrant 133C002585"

If the asset type and ID are not known (user did not associate the leak to an asset) please have the subject as:
"Leak reported on unknown asset"

**Comment by kanglu666** [comment]
updated, please clear cache and test

**Comment by alanfoster99** [comment]
Confirmed and closed
