### ISSUE TITLE
Leak Detection - Report - Typo

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#106]
Please correct "FEATUER TYPE:" to be "FEATURE TYPE:"

**Comment by tarheelgis** [comment]
Cannot seem to locate this in the project. Can you provide me a little more detail? Thanks!

**Comment by alanfoster99** [comment]
http://dpwview.baltimorecity.gov/LeakReport/LeakReport.aspx?LeakID=df68076c-4f04-0ee8-1f23-b936b8a4878f

Check out the first line – right side, after leak object ID

**Comment by kanglu666** [comment]
updated

**Comment by alanfoster99** [comment]
Confirmed and closing
