### ISSUE TITLE
Leak Detection - Zoom to Leak ID

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#109]
Please add a button to the interface allowing the user to search by leak ID.

Workflow should be:

User clicks button on map interface
App asks "Please enter Leak ID:"
User inputs leak ID into form
If ID found, please zoom the map to the location
If ID does not exist, please return error message "No leak found with that ID" and require to press "Okay" button

**Comment by kanglu666** [comment]
deployed on dev, please test:

http://dpw-gw03dev-srv/water/leakwebapi/index.aspx

**Comment by alanfoster99** [comment]
Looks good -- please change error message for alpha search from:
"Please enter correct Leak Object ID Number"
to:
"Please enter a valid ID"

**Comment by kanglu666** [comment]
updated

**Comment by alanfoster99** [comment]
Has this been deployed to the City?  I have cleared cache and reloaded, but am not seeing it.

**Comment by kanglu666** [comment]
on dev server: http://dpw-gw03dev-srv/water/leakwebapi/index.aspx
i will push to prod at night

**Comment by alanfoster99** [comment]
Looks good on dev -- will close once verified functional on production.  Please proceed with moving to production in the evening.

**Comment by alanfoster99** [comment]
Confirmed and closing
