### ISSUE TITLE
Leak Detection - Meter Information

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#111]
The app is recording the Meter Number for leaks on meters, not the FacilityID -- please change it to use FacilityID

![image](https://cloud.githubusercontent.com/assets/7118831/3912100/b57dc05e-2327-11e4-98c8-959efa3276d9.png)

**Comment by kanglu666** [comment]
Joe, please update the meter layer in map services, use "FacilityID" as  the displayField.
this will auto fix this issue

**Comment by JMurk** [comment]
Should be updated in both dev and prod.

**Comment by alanfoster99** [comment]
Confirmed and closing
