### ISSUE TITLE
Leak Detection - New Leak - Leak Status

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#112]
Please add capability to track if a leak is a customer side leak:

Add the following button to the leak form:

"Customer Side"

Please place this at the top of the form, between "Save" and "Email"

Joe, please add to the schema, then assign to Lu.

Lu, please update the app and the report to show this information.

Workflow will be user will create leak, save as usual; user taps "Customer Side"; splash window asks "Do you want to mark this leak as a customer side leak?  If so, please notify customer of leak."  "No" returns user to form, "Yes" sets status as "Customer Side" and closes the leak report from further edits.  Report will need to be emailed.

**Comment by kanglu666** [comment]
Joe, please update the Leak_Detection_Map map service to add a "Customer Side Leak" layer.

**Comment by kanglu666** [comment]
done a city dev, please test

**Comment by alanfoster99** [comment]
Lu,
Where is the new button?  I have cleared cache, used incognito mode, unable to find?  Am using dev.

**Comment by kanglu666** [comment]
in the top bar of the leak detail form. between save and email
![1](https://cloud.githubusercontent.com/assets/6352480/4458365/4bc33fe0-48a2-11e4-96f1-6b3d912bd77b.JPG)

**Comment by alanfoster99** [comment]
Looks good -- please push to Prod.

**Comment by kanglu666** [comment]
Joe, please update the Leak map service at city prod.
we can do this this weekend

**Comment by JMurk** [comment]
Map service updated for prod.

**Comment by kanglu666** [comment]
done at city prod, ready for testing

**Comment by alanfoster99** [comment]
Confirmed and closing
