### ISSUE TITLE
Leak Detection - Data - User Tracking

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#114]
The app is currently reporting the last user; Madeleine has requested that we change this to report the first user (reporter).  Should we update the schema to record this and report it, or simply change the app to only record the first user?

**Comment by kanglu666** [comment]
both options are fine for me. you decide

**Comment by alanfoster99** [comment]
After discussing with Amy, we need to add a field to the schema; she wants to retain last user in the table, but agrees we should include "reported by" in the report.

Please add a field to the feature class to track "reported by", then update the app to record the leak creator as the "reported by" individual; please change the report to show "Reported By:" instead of last editor.

**Comment by JMurk** [comment]
Schema change made in dev, will change in prod Saturday morning.

**Comment by JMurk** [comment]
Schema updated in prod.

**Comment by kanglu666** [comment]
both app and report have been updated at city DEV, please test

**Comment by alanfoster99** [comment]
Looks good, please update at Production.  Thank you.

**Comment by kanglu666** [comment]
Done on prod

**Comment by alanfoster99** [comment]
Confirmed and closing.
