### ISSUE TITLE
Leak Detection - Locator Search Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/Leak_Detection_Issues#116]
**Issue:**  When searching for an address in the locator, the application gets stuck on the loading screen.

![image](https://cloud.githubusercontent.com/assets/5805454/4558992/794ac45c-4ee6-11e4-8a89-260d93a76a73.png)

**Resolution:**  Please investigate and resolve ASAP.

**Comment by kanglu666** [comment]
fixed, please clear cache and test

**Comment by JMurk** [comment]
Confirmed complete.
