### ISSUE TITLE
Leak Detection - Report - Error

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#118]
The current leak report is empty when being sent out.  Please correct this quickly, this is a high priority bug.

http://dpwview.baltimorecity.gov/LeakReport/LeakReport.aspx?LeakID=bc62d474-68cd-23a0-1bc2-a8cbb3319022

**Comment by kanglu666** [comment]
should be fixed

**Comment by alanfoster99** [comment]
Confirmed and closing
