### ISSUE TITLE
Leak Detection - Leak IDs

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#119]
Please create a new leak ID field in the leak table, and populate with the "old" human-friendly leak IDs.  Once created, please iterate the new field to be the human friendly leak ID and no longer use ObjectID.

**Comment by JMurk** [comment]
This should all be completed.  Alan, please confirm and close.

**Comment by alanfoster99** [comment]
Confirmed and closing
