### ISSUE TITLE
Leak Detection - Survey Details - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#12]
Please set the default state of the Noise Code to be "no noise" instead of blank.

![image](https://cloud.githubusercontent.com/assets/7118831/2646233/59afaddc-bf3b-11e3-9023-1bcd9a5360ea.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed
