### ISSUE TITLE
Leak Detection - Leak - Data structure

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#120]
Please add the following status:

CLOSED - NOT REPAIRED

**Comment by jday3** [comment]
The status will now be displayed if the leak has this status, but it cannot be set in the app. This is currently in dev

**Comment by alanfoster99** [comment]
Thanks -- couple of things.  Let's change the status to be "Not Found"; the field can't be more than 20 characters, and I need to track this more than not repaired.

**Comment by jday3** [comment]
The status is now "Not Found", on dev

**Comment by alanfoster99** [comment]
Thanks -- sitting on this again; not sure if needs to be symbolized or not

**Comment by alanfoster99** [comment]
Closing for now
