### ISSUE TITLE
Leak Detection - Leak Form

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#121]
Please change the spelling of "Occurrance" to be "Occurrence"

![image](https://cloud.githubusercontent.com/assets/7118831/5572038/c47d286e-8f66-11e4-8942-49fdd5a2c837.png)

**Comment by jday3** [comment]
Fixed on dev

**Comment by alanfoster99** [comment]
Please deploy to prod

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed and closing
