### ISSUE TITLE
Leak Detection - Historical Leaks Broken

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#122]
When viewing a historical leak link, the following error is given:

![image](https://cloud.githubusercontent.com/assets/7118831/5779201/df7ce094-9d6e-11e4-808f-5cf0b75b57e5.png)

You can see this by querying current leak 46911

**Comment by jday3** [comment]
Where are you trying to access the historical leak info from? Also, is this on production, dev, or both?

**Comment by alanfoster99** [comment]
This is from the leak app on production -- identify a historical leak and the link is broken:

![image](https://cloud.githubusercontent.com/assets/7118831/5900935/22c987ce-a53c-11e4-90e5-1e987146b04e.png)

**Comment by jday3** [comment]
Fixed

**Comment by alanfoster99** [comment]
Confirmed and closing
