### ISSUE TITLE
Leak Detection - Photos not uploading

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#123]
There seems to be a server-side limit to the size of photo allowed to be attached.  3.5 MB works, 4.5 does not, server times out and gives the following error.  Is this something we can adjust, or is it imposed by MOIT?  If we cannot adjust it, we need to have an error message alerting the user to reduce the image size.  However, these are native iPad resolutions, so not many users will know how to resize...

Server Error in '/Water/LeakWebApi' Application.

Maximum request length exceeded.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Web.HttpException: Maximum request length exceeded.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[HttpException (0x80004005): Maximum request length exceeded.]   System.Web.HttpRequest.GetEntireRawContent() +9553280   System.Web.HttpRequest.get_InputStream() +41   System.Web.HttpRequestWrapper.get_InputStream() +9   System.Web.Http.WebHost.HttpControllerHandler.ConvertRequest(HttpContextBase httpContextBase) +234   System.Web.Http.WebHost.HttpControllerHandler.BeginProcessRequest(HttpContextBase httpContextBase, AsyncCallback callback, Object state) +79   System.Web.Http.WebHost.HttpControllerHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +301   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18446

**Comment by jday3** [comment]
@kanglu666, you worked mainly on this functionality. Do you remember any size limitations?

**Comment by jday3** [comment]
Sorry for the delay on this. I raised the limit, so now users should be able to upload hi res images taken with tablets/smart phones.

**Comment by jday3** [comment]
Updated on dev and prod

**Comment by alanfoster99** [comment]
Closing, thanks
