### ISSUE TITLE
Leak Detection - Leak Form

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#124]
On the leak detection form, please change "SR Number" to "Leak to Locate ID"; please make this update on the report as well.

![image](https://cloud.githubusercontent.com/assets/7118831/6639646/a3015558-c967-11e4-84cf-8f326bff97f9.png)

**Comment by jday3** [comment]
Done on dev/prod

**Comment by alanfoster99** [comment]
Confirmed and closing
