### ISSUE TITLE
Leak Detection - Discrepancy Tool

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#127]
The Add Discrepancy Tool in the Leak Detection app has no functionality, and serves only as a place holder.  Please enable the tool to capture and report discrepancies.

**Comment by taojun545** [comment]
@alanfoster99 It seems "Add Discrepancy Tool" works on both dev and prod. Please confirm which one is not working. Thanks.

**Comment by alanfoster99** [comment]
You are correct -- seems to be functioning.
