### ISSUE TITLE
Leak Detection - Leak - 2016 missing

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#128]
Please add 2016 to the picker for leak and survey dates.
![image](https://cloud.githubusercontent.com/assets/7118831/12091187/2d206162-b2c3-11e5-8256-02ac89f8da84.png)

**Comment by JMurk** [comment]
Per Jesse:  "the correct approach should be to use the current date to calculate the list of years instead of a hard-coded list."

**Comment by alanfoster99** [comment]
Good in test -- please push to PROD.

**Comment by alanfoster99** [comment]
Confirmed and closing
