### ISSUE TITLE
Leak Detection - New Leak - Syntax

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#18]
Please change the popup window text from "Can you Identify the Leak Feature" to "Can you Identify Which Object is Leaking?"

![image](https://cloud.githubusercontent.com/assets/7118831/2647335/78cb1248-bf49-11e3-8e13-1fa24907dbe8.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
