### ISSUE TITLE
Leak Detection - New Leak Message Box - Typo

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#2]
Please change the text of "Tap on MAP" to read "Tap on Map"

![image](https://cloud.githubusercontent.com/assets/7118831/2617159/0bac7234-bc0f-11e3-90f7-6a28f1db751e.png)

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed complete.  Will close.
