### ISSUE TITLE
Leak Detection - Edit Leak - Minor Bug

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#23]
When a user creates a new leak and saves it, the "Last Edit User" field is not getting updated.  Please update the field appropriately.

![image](https://cloud.githubusercontent.com/assets/7118831/2682362/c0b5d104-c199-11e3-85e5-cd56497a52f5.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Not populating for me, please revisit.

**Comment by kanglu666** [comment]
tested, it's working for me.
when you are in office, we can work through this

**Comment by kanglu666** [comment]
please test

**Comment by alanfoster99** [comment]
Verified and closed
