### ISSUE TITLE
Leak Detection - Edit Survey - Minor Bug

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#24]
When a user creates a new leak and saves it, the "Last Edit User" field is not getting updated. Please update the field appropriately.

![image](https://cloud.githubusercontent.com/assets/7118831/2682384/323154e8-c19a-11e3-9db8-131623a287c2.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Not updating, showing last user as "Null" -- please revisit.

**Comment by kanglu666** [comment]
work for me. when you are in office, we can test it

**Comment by alanfoster99** [comment]
Verified working -- closed
