### ISSUE TITLE
Leak Detection - New Survey - Syntax

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#26]
Please change "Can you Identify the Survey Feature?" to "Is the Survey Feature Shown on the Map?"

![image](https://cloud.githubusercontent.com/assets/7118831/2682680/ce463caa-c19e-11e3-93f0-1fc99b9e78b9.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Verified and closed.
