### ISSUE TITLE
Leak Detection - Identify - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#29]
Please remove the splash screen asking "Identify Leaks or Surveys?  Tap on Map!"

![image](https://cloud.githubusercontent.com/assets/7118831/2682758/5d199d2c-c1a0-11e3-9ff1-e4c775a9a80f.png)

**Comment by kanglu666** [comment]
kepp it as is

**Comment by alanfoster99** [comment]
Needs to be removed -- requested by users -- please revisit.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed -- closed.
