### ISSUE TITLE
Leak Detection - Leak - Syntax

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#30]
On the edit leaks page, please change "Last Edit Date" to "Last Edit" and display date and time, not just date.

![image](https://cloud.githubusercontent.com/assets/7118831/2682778/9ece35ca-c1a0-11e3-8bb5-b194cfb910c6.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Please change "Last Edit Date" to "Last Edit"

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed -- closed.
