### ISSUE TITLE
Leak Detection - New Leak - Syntax

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#32]
Please add capability to include fittings in the possible leaking features.  Joe and Alan will need to add these to the map before this can be done.

**Comment by alanfoster99** [comment]
Fittings data are now in the map service -- please proceed with adding them to the possible leaking features and the legend.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
