### ISSUE TITLE
Leak Detection - General - Settings

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#34]
Please set the search radius to be dependent upon the zoom level, so that as the user zooms in, the radius adjusts to a smaller and smaller size, appropriate to the zoom level.

**Comment by kanglu666** [comment]
i will still keep the radius bar for user to set the value.

**Comment by alanfoster99** [comment]
Okay -- will see with workflow, may need to revisit.  Closing for now.
