### ISSUE TITLE
Leak Detection - New Survey - Survey ID

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#36]
The Survey ID is not currently populated with an easy to read number -- please generate a sequential, easy to read number.

![image](https://cloud.githubusercontent.com/assets/7118831/2682925/a012effa-c1a2-11e3-8d73-0aa79cb4b381.png)

**Comment by kanglu666** [comment]
the same as Leak_ID.
if we do need a easy ready number at the app side. we need to update the data base.

just let me know, if we do need one.

**Comment by alanfoster99** [comment]
Verified and good as is -- users do not need an ID number.  Closing.
