### ISSUE TITLE
Leak Detection - New Leak - Lead ID

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#37]
The Leak ID is not currently populated with an easy to read number -- please generate a sequential, easy to read number.

![image](https://cloud.githubusercontent.com/assets/7118831/2682935/d4ae1eb0-c1a2-11e3-83db-18e1d2403d27.png)

**Comment by kanglu666** [comment]
Leak Id field in database have values guid. i will hide this at the app side.
if we do need a easy read number field, we need to update the data base, add an new filed called: Leak_NO.
Just let me know, if we do need this easy ready number.

**Comment by alanfoster99** [comment]
Got it -- verified as described.  Will discuss with project leaders and let you know if simple ID is needed.  Closing.
