### ISSUE TITLE
Leak Detection - Leak Details - Typo

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#4]
Please change "Occurence Date" to "Occurrence Date"

![image](https://cloud.githubusercontent.com/assets/7118831/2617581/6fcebc7c-bc14-11e3-9f6e-bfd391e2a16a.png)

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed complete.  Will close.
