### ISSUE TITLE
Leak Detection - Layers - Missing Data

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#46]
Please update the layer symbology for leaks to mirror the updated symbols in the new map service.  There are updated symbols for meters, services, and fittings were added.

![image](https://cloud.githubusercontent.com/assets/7118831/2743361/de358dc2-c712-11e3-92af-2f1fa5771fc0.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
