### ISSUE TITLE
Leak Detection - Edit Leak - Work flow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#48]
Please add a button called "Repaired" to the right of the "Email" button. 
When the user clicks the "Repaired" button, have a splash screen pop up with the following message:
"This will mark this leak as repaired and close out the record.  Continue?"
If the user clicks "No" please return them to the editor page for leaks.  If the user clicks "Yes" please update the symbology of the leak, and move it to the historical leaks data.

![image](https://cloud.githubusercontent.com/assets/7118831/2743494/1a5fc9e6-c715-11e3-86a0-f66fd727ae1a.png)

**Comment by kanglu666** [comment]
done, please clear browser cache and test

**Comment by alanfoster99** [comment]
The user should still be able to edit and save the record after it has been emailed.  The record will not be locked until it is marked as repaired.  Once the user has emailed the Leak, they will still need access to edit all fields as well as add / delete photos, and continue to save the record.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed
