### ISSUE TITLE
Leak Detection - Leak - Field size

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#51]
The current limit to the SR Number field is 10 characters.  If the user enters more than 10 characters, the interface displays the loading popup, but never terminates.  Please check the length of what the user enters, and provide a warning message if they exceed the length.

![image](https://cloud.githubusercontent.com/assets/7118831/2743679/e87eb0b0-c717-11e3-90cd-ac2b2262f94d.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
