### ISSUE TITLE
Leak Detection - New Water Map Service

### ISSUE THREAD

**Issue by JMurk** [JMurk/Leak_Detection_Issues#57]
A new Map service has been created on GW03 for use in the leak detection application.  Please use Leak_Detection_App_Water_Features in place of 1108_Waterdev.

**Comment by alanfoster99** [comment]
Additionally, please make sure the report is also using this service for its live map instance.

**Comment by kanglu666** [comment]
done

**Comment by tarheelgis** [comment]
Just saw the note about the report for this one will post a change shortly

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Can't tell a difference in the report -- is this due to the scale of the map in the report?

**Comment by kanglu666** [comment]
assign this to Eric. he needs to update the mapservice for the report

**Comment by tarheelgis** [comment]
Added please test

**Comment by alanfoster99** [comment]
Confirmed and closed.
