### ISSUE TITLE
Leak Detection - New Leak - Work Flow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#6]
When creating a new leak, the user confirms that they wish to create a new leak, and taps the location on the map.  The follow-up question asks "Can you Identify the Leak Feature?"  If the user selects No, they are exited out of the process.  Please change so that if the user selects No, they are forwarded directly to the Leak Details page.

![image](https://cloud.githubusercontent.com/assets/7118831/2617897/bdc87efa-bc18-11e3-8888-46a1e38c60b5.png)

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed complete.  Will close.
