### ISSUE TITLE
Leak Detection - New Leak - Point Location

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#61]
Currently, when a user creates a new leak and associates it to a liner feature (main, service, etc) the point is moved to the center of the feature.  Please retain the location of the original click as the X, Y of the leak, and do not move the point.  The client has indicated that this will cause confusion and errors if left as is.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
