### ISSUE TITLE
Leak Detection - General -Layers

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#62]
The initial extent of the map is set so that the southern portion of the city is being cut off by the interface.  Please re-center the map to correct this.

![image](https://cloud.githubusercontent.com/assets/7118831/2764798/172e3920-ca1b-11e3-818a-64def4f17e5e.png)

**Comment by kanglu666** [comment]
use ipad/ or adjust you chrome screen to look like a ipad

**Comment by alanfoster99** [comment]
Confirmed and closed.
