### ISSUE TITLE
Leak Detection - General - Zoom to my location tool

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#63]
Please include an accuracy bubble showing the radius of accuracy for the geolocation signal, and zoom in / out to the accuracy bubble when the user selects the tool.  Please set a lower zoom threshold so the interface does not zoom in beyond a legible extent.

![image](https://cloud.githubusercontent.com/assets/7118831/2782001/69caab8c-cb1a-11e3-8316-f7e2139b6f9b.png)

**Comment by kanglu666** [comment]
done, please use ipad to test.
if use chrome, the gps accuracy is really bad.
then the bubble will be super larger.

**Comment by alanfoster99** [comment]
Confirmed and closed
