### ISSUE TITLE
Leak Detection - Map Layers - Historical Leaks

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#66]
Please include the "old" leaks database to be as a single symbol, entitled "Historical Leaks"; all 4 classes will be symbolized by this.  Alan to assist

**Comment by JMurk** [comment]
I've updated the map service to show one symbol for ALL records in the old leak database.  To change the name of the feed, assign to Lu.

**Comment by alanfoster99** [comment]
Lu, please change the name of the feed to "Historical Leaks"; add to the Leak Detection group.

**Comment by kanglu666** [comment]
done, historical leak layer has been added into leak detection app. by default it's turned off.

**Comment by alanfoster99** [comment]
Confirmed -- closed
