### ISSUE TITLE
Leak Detection - Submit Leak - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#67]
Please replace the "Repaired" button with a "View Report" button, which will allow the user to view the dynamically created report.

![image](https://cloud.githubusercontent.com/assets/7118831/2833988/cb26d7a4-cfd7-11e3-8c1c-08f98a2e6c24.png)

**Comment by kanglu666** [comment]
"Repaired" button is used to change the status from "emailed" to "repaired". 
Do you want to change the work flow?

**Comment by alanfoster99** [comment]
We are changing the workflow; eventually the repaired status will be provided by a link to Cityworks.  We aren't there yet, so let's leave this as is until we figure out that piece.  We do need a view report function, though.  Will log as separate request.
