### ISSUE TITLE
Leak Detection - General - Create Discrepancy Tool

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#68]
Please add a button for Discrepancy Tool -- entitle "Log Discrepancy"

Provide a form for the user to input pertinent information:

User selects Feature Class:  Water || Sewer || Storm
User selects Feature Type (based upon which Class is chosen)
User selects Discrepancy Type:  Feature Not In Map || Existing Feature || Cannot Locate Feature
User enters comments
(X,Y info from click; user name from session; status is created as active, but is not exposed to user)

User emails the discrepancy and it is sent to appropriate addresses.

Please interface with Joe to ensure this workflow will work with what he needs for Utility Viewer

**Comment by kanglu666** [comment]
need design and work flow.

**Comment by alanfoster99** [comment]
I believe Joe is working on this -- do you want assistance Joe?

**Comment by JMurk** [comment]
I'm working on the Feature Class design and the UV design/workflow.  You can work on the mobile app design if you want.

**Comment by alanfoster99** [comment]
Please get X, Y info from click, user name from session, and feature type from app and include with email of all information gathered from user form.

Wireframe is located at:
M:\2010\13101078\Reports\Geospatial\Leak Detection\Design\Wireframes\Discrepancy\Discrepancy_Wireframe

**Comment by kanglu666** [comment]
Adding new Discrepancy tool has been added in leak detection mobile app. please clear your browser cache and test.

**Comment by alanfoster99** [comment]
Please sort feature types alphabetically, and remove the second "Detailed Description of the Discrepancy"

**Comment by kanglu666** [comment]
Discrepancy tool for Leak Detection has been updated. please clear browser cache and test

**Comment by alanfoster99** [comment]
Looks good.  Closing.
