### ISSUE TITLE
Leak Detection - New Leak - SR Number

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#69]
Please add a field for the user to input SR Number, place above WO Number

![image](https://cloud.githubusercontent.com/assets/7118831/2846218/c0e34052-d09f-11e3-8e76-375c35be6f2b.png)

**Comment by kanglu666** [comment]
there is no WO Number field in the database. has SR Number field
do we need to update the schema?
right now, in the app, it's SR Number but shows as WO Number.

**Comment by alanfoster99** [comment]
Yes, we will need to update schema -- apparently both fields can be populated.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
