### ISSUE TITLE
Leak Detection - Delete Leak - Typo

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#7]
The message box asking the user if they wish to delete the leak record says:
"Are you sure to delete Leak Record?"

Please change this to:
"Are you sure you want to delete this Leak Record?"

![image](https://cloud.githubusercontent.com/assets/7118831/2618074/f3dad090-bc1a-11e3-9f51-fd8187aebac7.png)

**Comment by jday3** [comment]
Done

**Comment by alanfoster99** [comment]
Confirmed complete.  Will close.
