### ISSUE TITLE
Leak Detection - Survey Report - Create

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#71]
We need to get the Survey Points exporting to their own report; requested was the ability to create a report based on active record / screen extent; the report was requested to have:
o   Title information
o   WO & SR number (these will be separate fields)
o   Map showing Survey Points, but not leaks
o   Any comments
o   Any photos of the selected record

**Comment by tarheelgis** [comment]
completed please check when changes post

**Comment by alanfoster99** [comment]
Looks good, closing
