### ISSUE TITLE
Leak Detection - New Leak - View Report

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#72]
Once the user has emailed the report, please add a button, "View Report" which creates the dynamically generated report for the user.

![image](https://cloud.githubusercontent.com/assets/7118831/2846371/988b3176-d0a1-11e3-8747-40c358c97aec.png)

**Comment by kanglu666** [comment]
done, report button will show, after emailed the leak.
right now, the report is hitting KCI version. i will publish leak report at city side soon.

**Comment by alanfoster99** [comment]
Confirmed.  Created separate ticket for publishing to city side, so closing this request.
