### ISSUE TITLE
Leak Detection - New Leak - Save Message

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#73]
When the user saves the leak, the popup window needs to say:

"The record is saved but NOT emailed"

![image](https://cloud.githubusercontent.com/assets/7118831/2846394/d6dd74ca-d0a1-11e3-82f2-b838bae0790d.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Please set a condition to continue to watch the emailed status of the leak; right now, the "saved but not emailed" message only occurs once; the message needs to persist until the user carries out the email request.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed
