### ISSUE TITLE
Leak Detection - Email Leak - Popup Message

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#74]
If the user saves and emails a leak, and then presses the save button again, if the user goes back to the map tab, they are informed that it has not yet been saved.  Please change the logic to keep track of the latest status of the leak.

![image](https://cloud.githubusercontent.com/assets/7118831/2846406/fd5856a6-d0a1-11e3-810c-dc148d2f5fda.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
