### ISSUE TITLE
Leak Detection - Historical Leaks - Identify

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#75]
Please set the Historical Leaks as identifiable.  When the user identifies a historical leak, please provide the leak name and a hyperlink to the existing PDF.

**Comment by kanglu666** [comment]
Please provide me the work flow, all the PDFs.
Should i use the current "Leak_Attachment" table to link the documents to the leak record? or anyone will provide me an new one?

**Comment by alanfoster99** [comment]
I will pull together the work flow.  As to all the PDFs, all I have is what is here:
https://www.dropbox.com/s/dc0afvd846l1y4b/Leaks.zip
Your table lists 140 that I don't have in that archive, so I'm curious if there are any on the server that you know of?  The table that you have is the most current there is, I don't believe that anything should have changed since then -- we just need to find the missing PDFs.  Where on the server did you find that table?

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closing.
