### ISSUE TITLE
Leak Detection - Leak - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#77]
If the user saves and emails a leak, when they attempt to return to the map tab, a message pops up informing them that the leak has not been submitted.  Please correct the logical test.

![image](https://cloud.githubusercontent.com/assets/7118831/2862774/e9253a1a-d1f9-11e3-8654-7e2ff6af7197.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
