### ISSUE TITLE
Leak Detection - View Report - Repaired Leak issue

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#78]
Once a leak has been marked as "Repaired", if the user accesses the report, the map is not being generated.  Please correct this so that the map shows up on the report.

![image](https://cloud.githubusercontent.com/assets/7118831/2864680/5e36a352-d213-11e3-8873-76c6d9834cb2.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
