### ISSUE TITLE
Leak Detection - Leak Report - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#79]
Once a user has marked a leak as "Repaired", the report is no longer viewable once the user has returned to the map tab.  Please make it so that the report is always available once it has been emailed.

![image](https://cloud.githubusercontent.com/assets/7118831/2864924/9ab4f5d8-d216-11e3-92f5-76cb09613e7e.png)

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closed.
