### ISSUE TITLE
Leak Detection - New Leak - Work Flow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#8]
When associating a new leak with existing water features, if more features are reported than there is room for in the window, then these features are cut off and not displayed.  Please add a scroll bar to the "Leak Feature" window to allow the user to see all associated features.

![image](https://cloud.githubusercontent.com/assets/7118831/2618781/2bbf864e-bc26-11e3-88ee-21c31fb4d6ee.png)

**Comment by JMurk** [comment]
Alan- you have to hold the left click and push up with the mouse (because it is built for a tablet and using your finger).  It should be working ok.

**Comment by alanfoster99** [comment]
Functions properly when holding down left mouse button -- not a bug.  Closing. -Alan

**Comment by alanfoster99** [comment]
Tested and verified – closed.

Thanks!

-Alan
