### ISSUE TITLE
Leak Detection - Reports - Location Discrepancies

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#86]
Survey and leak points shown close to each other on the map view, are in the report offset from actual locations.  Is there a setting where we can force them to draw in the correct location?  See two attached images below:

![image](https://cloud.githubusercontent.com/assets/7118831/2960252/1931b2b4-dabb-11e3-94fa-5a04a7e0ba2b.png)

![image](https://cloud.githubusercontent.com/assets/7118831/2960254/1f932548-dabb-11e3-9130-9cdfa33310e4.png)

**Comment by tarheelgis** [comment]
Interesting. This definitely has to do with DPI vs map scale issues IMHO. Stock is 96 DPI but that prints like crap so I bumped it and all map services to 150 and adjusted the scale synchronously with all other services as well and it appears to have this effect. It was not noticeable on single point testing and other services appear to be lined up correctly. I will investigate

**Comment by alanfoster99** [comment]
Are the symbols being treated as labels instead of points?  Could that be part of the issue?

**Comment by tarheelgis** [comment]
Scaling issue is fixed. It turned out to be a combination of 2 things. I had a manual scaling factor combined with DPI mixed in with a setting the request did not like. Weird...

**Comment by alanfoster99** [comment]
Confirmed and closing
