### ISSUE TITLE
Leak Detection - Leak Report - Orientation

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#89]
Photos which are attached to leak reports are being rotated 90 degrees; please make sure they retain the original orientation.

![image](https://cloud.githubusercontent.com/assets/7118831/2975161/e9e5600a-db91-11e3-8c0f-44cf6704a5eb.png)

**Comment by tarheelgis** [comment]
Have we isolated that it is the report that is rotating the images and not the data entry application? It appears in my testing that the images are reading correctly based on the stored rotation of the file.

**Comment by alanfoster99** [comment]
You are correct -- Lu, please examine

**Comment by kanglu666** [comment]
done, if the photo come from ipad, it will auto rotate 90 when upload to server.

**Comment by alanfoster99** [comment]
Confirmed and closing

**Comment by alanfoster99** [comment]
Please check and see if methods exist to rotate images appropriately based upon source (web vs. iOS) -- if not, please default so iOS supplied images are displayed properly

**Comment by kanglu666** [comment]
done. when saving photos, the server will determine to rotate and save photos based on the the browser type.  Please test in Ipad and Chrome.

**Comment by alanfoster99** [comment]
Still not working correctly on iPad

**Comment by alanfoster99** [comment]
Abandoning for now
