### ISSUE TITLE
Leak Detection - Survey Report - Orientation

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#90]
Photos which are attached to survey reports are being rotated 90 degrees; please make sure they retain the original orientation.

![image](https://cloud.githubusercontent.com/assets/7118831/2975170/09b22904-db92-11e3-8a14-0a573705a745.png)

**Comment by tarheelgis** [comment]
Have we isolated that it is the report that is rotating the images and not the data entry application? It appears in my testing that the images are reading correctly based on the stored rotation of the file.

**Comment by alanfoster99** [comment]
You are correct -- Lu, please examine

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closing.

**Comment by alanfoster99** [comment]
Please check and see if methods exist to rotate images appropriately based upon source (web vs. iOS) -- if not, please default so iOS supplied images are displayed properly

**Comment by kanglu666** [comment]
done, please test Ipad and Chrome

**Comment by alanfoster99** [comment]
Not working in iPad for viewing report -- photo taken on iPad displays correctly when viewed in the Image Manager, but not when viewed on iPad in the report.  Photos display fine in Chrome when uploaded from iPad.

**Comment by alanfoster99** [comment]
Abandoning for now
