### ISSUE TITLE
Leak Detection - Edit Survey - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#91]
Please change the workflow for the edit survey tab to be as follows:

Please make "Edit Photos", "Delete" and "Save" always available, regardless of survey status

Please remove the "Email" button

Please make "View Report" available as soon as the user has pressed the "Save" button

**Comment by kanglu666** [comment]
work flow issue: when user create multiple surveys. after click "Save"
then ""View Report"" button available? which survey to view is a problem.

**Comment by kanglu666** [comment]
updated:  "Edit Photos", "Delete" and "Save" always available, 
"Email" button renamed to "Submit" which will change the status of the Survey.

**Comment by alanfoster99** [comment]
Do we even need the submit button?  View Report is showing up after saving surveys.
Can the view report center at the user click which is the center of the selection buffer?

**Comment by kanglu666** [comment]
"Submit" button is control the Survey Status of the survey change from  "In Progress" to "Submit"

**Comment by alanfoster99** [comment]
Status is no longer needed as per our discussion; see #94 for further info

**Comment by alanfoster99** [comment]
Confirmed and closing.
