### ISSUE TITLE
Leak Detection - Edit Leaks - Email

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#93]
Please email reports to alan.foster@kci.com for testing purposes.

**Comment by kanglu666** [comment]
email leak report plunged in. please clear browser cache, test.
we need to talk about the survey part.
"remove email button" means not email survey report?

**Comment by alanfoster99** [comment]
correct -- surveys will not always be emailed, so we just want them to be able to create the survey data and then view the report

**Comment by kanglu666** [comment]
done.

**Comment by alanfoster99** [comment]
Confirmed and closing
