### ISSUE TITLE
Leak Detection - New Leak - Bug

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#97]
On Android platform, creating a new leak locks the system.  If user selects that they cannot identify the leaking feature, the system goes to the Leaks Tab and locks; if they indicate they can identify the feature, the system populates the list of available features but does not progress beyond the list.

**Comment by kanglu666** [comment]
all city mobile apps are designed for ipad.

**Comment by JMurk** [comment]
This bug should still be resolved.  The City has no standard tablet that they use, therefore it is very possible android devices will be used.

Alan- what are the crews going to be using immediately?

**Comment by alanfoster99** [comment]
We have told them to use iOS, but no verification. There is an android at the office for testing.

Alan E. Foster

Senior Geospatial Analyst, KCI Technologies, Inc.
1.410.316.0812tel:1.410.316.0812
alan.foster@kci.commailto:alan.foster@kci.com

Lead, UAMD Data Management Section
1.410.396.0022tel:1.410.396.0022

On Jun 20, 2014, at 5:32, "Joe Murk" <notifications@github.com<mailto:notifications@github.com>> wrote:

This bug should still be resolved. The City has no standard tablet that they use, therefore it is very possible android devices will be used.

Alan- what are the crews going to be using immediately?

**Comment by alanfoster99** [comment]
I will be at the office this afternoon and can run through the testing on the Android device when I am there.

**Comment by alanfoster99** [comment]
Testing complete on Android platform, no issues encountered.  Closing.
