### ISSUE TITLE
Leak Detection - New Leak - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#98]
Please create a record of the server-time and date when the leak was created.  This should not be user editable.  Please call this "Record Date".

**Comment by kanglu666** [comment]
do you want to add an new field "Record_Date" into the leak feature class? update the db schema

**Comment by alanfoster99** [comment]
Yes please.

Alan E. Foster

Senior Geospatial Analyst, KCI Technologies, Inc.
1.410.316.0812tel:1.410.316.0812
alan.foster@kci.commailto:alan.foster@kci.com

Lead, UAMD Data Management Section
1.410.396.0022tel:1.410.396.0022

On Jun 18, 2014, at 12:04, "lu" <notifications@github.com<mailto:notifications@github.com>> wrote:

do you want to add an new field "Record_Date" into the leak feature class? update the db schema

**Comment by JMurk** [comment]
Schema has been updated.  Lu, please update.

**Comment by kanglu666** [comment]
done

**Comment by alanfoster99** [comment]
Confirmed and closing.
